[package]
name = "rbench"
version = "0.0.1"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]

serde = "*"
serde_macros = "*"

[dependencies.eventual]

git = "https://github.com/carllerche/eventual"
